'''

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Created on 29 Aug 2016

@author: James
'''
class Problem02(object):
    
    def __init__(self):
        pass
    
    def find_range_below(self, upperbound):
        fibonacci_list = [1,2]
        
        while upperbound >= fibonacci_list[-2] + fibonacci_list[-1]:
            fibonacci_list.append(fibonacci_list[-2] + fibonacci_list[-1])
            
        return fibonacci_list
    
    def sum_even_range(self, seq):
        sum_even_numbers = 0
        for i in seq:
            sum_even_numbers += i if i%2==0 else 0
            
        return sum_even_numbers